name: CI
on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch

jobs:
  job1:
    runs-on: ubuntu-latest
    name: Build and deploy to minikube
    steps:
    - uses: actions/checkout@v4  # Checkout the code
      with:
        repository: your-repo-name

    - name: Start minikube
      uses: medyagh/setup-minikube@latest

    - name: Try the cluster
      run: kubectl get pods -A

    - name: Build image
      run: |
        minikube image build -t local/devex:v1 .

    - name: Deploy to minikube
      run: |
        kubectl apply -f deploy/k8s.yaml
        kubectl wait --for=condition=ready pod -l app=local-devex

    - name: Test service URLs
      run: |
        minikube service list
        minikube service local-devex-svc --url
        curl $(minikube service local-devex-svc --url)
